package org.jansaarthi.app.ui.localization

import org.jansaarthi.app.data.model.AppLanguage

data class JanSaarthiStrings(
    // App Branding & Header
    val appTitle: String,
    val appSubtitle: String,
    val govIndia: String,
    val officialPortal: String,
    val verifiedBadge: String,

    // Accessibility
    val languageLabel: String,
    val textSizeLabel: String,
    val normalSize: String,
    val largeSize: String,

    // Auth - Common & Login
    val citizenLogin: String,
    val loginSubtitle: String,
    val withPasswordTab: String,
    val withOtpTab: String,
    val mobileOrEmailLabel: String,
    val mobileOrEmailPlaceholder: String,
    val passwordLabel: String,
    val passwordPlaceholder: String,
    val forgotPassword: String,
    val loginButton: String,
    val sendOtpButton: String,
    val verifyAndLoginButton: String,
    val enterOtpLabel: String,
    val sentViaSms: String,
    val resendOtpIn: String,
    val resendOtpButton: String,
    val changeNumber: String,
    val orDivider: String,
    val continueAsGuest: String,
    val continueAsGuestSubtitle: String,
    val newToJanSaarthi: String,
    val registerSignUp: String,

    // Auth - Sign Up
    val citizenRegistration: String,
    val signUpSubtitle: String,
    val fullNameLabel: String,
    val fullNamePlaceholder: String,
    val mobileNumberLabel: String,
    val emailOptionalLabel: String,
    val chooseSecurityMethod: String,
    val createPasswordTab: String,
    val directOtpTab: String,
    val confirmPasswordLabel: String,
    val confirmPasswordPlaceholder: String,
    val termsAgreementPre: String,
    val termsOfService: String,
    val andWord: String,
    val privacyPolicy: String,
    val createAccountButton: String,
    val alreadyRegistered: String,
    val loginHere: String,
    val privacyPledge: String,

    // Forgot Password
    val resetPasswordTitle: String,
    val resetPasswordSubtitle: String,
    val updatePasswordButton: String,
    val resetSuccessTitle: String,
    val resetSuccessSubtitle: String,
    val proceedToLogin: String,

    // State Selection Onboarding
    val stepProfileSetup: String,
    val stateSelectionTitle: String,
    val stateSelectionSubtitle: String,
    val searchStatePlaceholder: String,
    val allStatesTab: String,
    val statesOnlyTab: String,
    val utsOnlyTab: String,
    val popularTab: String,
    val selectedStateLabel: String,
    val confirmStateButton: String,
    val changeStateLaterNote: String,
    val capitalLabel: String,
    val zoneLabel: String,
    val unionTerritoryBadge: String,

    // Home Dashboard
    val welcomeCitizen: String,
    val citizenWelfareTitle: String,
    val citizenWelfareSubtitle: String,
    val activeApplicationsLabel: String,
    val dbtStatusLabel: String,
    val dbtActive: String,
    val searchSchemesPlaceholder: String,
    val filterGovernanceLevel: String,
    val allApplicableSchemes: String,
    val centralNationwide: String,
    val stateSpecificSchemes: String,
    val centralBadge: String,
    val stateBadge: String,
    val guestModeActive: String,
    val guestModeSubtitle: String,
    val signInButton: String,
    val changeStateLink: String,

    // Categories
    val categoryFarmers: String,
    val categoryHealthcare: String,
    val categoryHousing: String,
    val categoryEducation: String,
    val categoryPensions: String,
    val categoryFood: String,

    // Scheme Detail Modal (Eligibility, Benefits, Documents, Steps)
    val schemeDetailsTitle: String,
    val eligibilityHeader: String,
    val benefitsHeader: String,
    val documentsHeader: String,
    val stepsHeader: String,
    val applyOnlineButton: String,
    val closeButton: String,

    // Profile & Settings
    val profileTitle: String,
    val profileName: String,
    val profileMobile: String,
    val profileEmail: String,
    val profileResidentState: String,
    val changeResidentStateButton: String,
    val profileLanguageTitle: String,
    val changeLanguageButton: String,
    val selectLanguageTitle: String,
    val signOutButton: String,
    val confirmSignOutTitle: String,
    val confirmSignOutMessage: String,
    val cancelAction: String,

    // Help & Attribution
    val citizenHelpdesk: String,
    val tollFreeNumber: String,
    val dpdpCompliant: String,
    val nicAttribution: String,

    // Notifications
    val notificationTitle: String,
    val notificationDbtAlert: String,
    val notificationDeadlineAlert: String,

    // =============================================================
    // COMPREHENSIVE LOCALIZATION EXTENSIONS FOR COMPLETE FRONTEND
    // =============================================================

    // Navigation
    val navHome: String,
    val navSchemes: String,
    val navApplications: String,
    val navDocuments: String,
    val navProfile: String,
    val navBack: String,

    // Common Buttons
    val applyNow: String,
    val checkEligibility: String,
    val viewDetails: String,
    val saveScheme: String,
    val savedBadge: String,
    val unsaveScheme: String,
    val downloadAction: String,
    val uploadDocumentAction: String,
    val syncDigiLockerAction: String,
    val searchAction: String,
    val filterAction: String,
    val clearFiltersAction: String,
    val applyFiltersAction: String,
    val resetFiltersAction: String,
    val retryAction: String,
    val confirmAction: String,
    val submitAction: String,
    val exploreSchemesAction: String,
    val viewAllAction: String,
    val trackStatusAction: String,
    val shareAction: String,
    val addDocumentAction: String,
    val viewDocumentAction: String,
    val changeStateAction: String,
    val changeLanguageAction: String,

    // Labels & Badges
    val centralGovernmentLabel: String,
    val stateGovernmentLabel: String,
    val unionTerritoryLabel: String,
    val allSchemesLabel: String,
    val dbtActiveLabel: String,
    val verifiedStatusLabel: String,
    val requiredBadge: String,
    val optionalBadge: String,
    val readyBadge: String,
    val missingBadge: String,
    val ministryLabel: String,
    val departmentLabel: String,
    val benefitLabel: String,
    val eligibilityLabel: String,
    val documentsRequiredLabel: String,
    val applicationProcessLabel: String,
    val keyHighlightsLabel: String,
    val lastUpdatedLabel: String,
    val readinessScoreLabel: String,
    val referenceNumberLabel: String,
    val applicationDateLabel: String,
    val prototypeDisclaimer: String,
    val eligibleStatusLabel: String,
    val familyBenefitLabel: String,
    val conditionalMatchLabel: String,
    val universalCitizenLabel: String,
    val overviewLabel: String,

    // Filters & Tabs
    val filterByLevelLabel: String,
    val filterByCategoryLabel: String,
    val filterByStateLabel: String,
    val sortByLabel: String,
    val sortPopularityLabel: String,
    val sortAmountHighToLowLabel: String,
    val sortNewestLabel: String,
    val onlyDbtLabel: String,
    val targetBeneficiaryLabel: String,
    val allCategoriesLabel: String,
    val allStatesLabel: String,
    val allFilterLabel: String,
    val centralFilterLabel: String,
    val stateFilterLabel: String,
    val utFilterLabel: String,
    val filterStatusDraft: String,
    val filterStatusApplied: String,
    val filterStatusUnderProcess: String,
    val filterStatusApproved: String,
    val filterStatusRejected: String,
    val filterStatusCompleted: String,

    // Empty States
    val noSchemesFoundTitle: String,
    val noSchemesFoundDesc: String,
    val noApplicationsTitle: String,
    val noApplicationsDesc: String,
    val noDocumentsTitle: String,
    val noDocumentsDesc: String,
    val noSavedSchemesTitle: String,
    val noSavedSchemesDesc: String,
    val noSearchResultsTitle: String,
    val noSearchResultsDesc: String,

    // Errors
    val errorGenericTitle: String,
    val errorGenericDesc: String,
    val errorNetworkTitle: String,
    val errorNetworkDesc: String,
    val errorSubmissionFailed: String,
    val errorFillRequiredFields: String,
    val errorInvalidInput: String,

    // Help & Support
    val helpTitle: String,
    val helpSubtitle: String,
    val tollFreeHelplineLabel: String,
    val helplineHoursLabel: String,
    val faqTitleLabel: String,
    val contactUsLabel: String,
    val grievanceRedressalLabel: String,
    val dpdpActComplianceLabel: String,

    // Settings
    val settingsTitleLabel: String,
    val easyModeLabel: String,
    val easyModeDesc: String,
    val languagePreferenceLabel: String,
    val notificationsSettingLabel: String,
    val privacySecurityLabel: String,
    val accountDetailsLabel: String,
    val residentStateSettingLabel: String,
    val digiLockerStatusLabel: String,
    val aboutJanSaarthiTitle: String,
    val aboutJanSaarthiDesc: String,
    val logoutDialogTitle: String,
    val logoutDialogMessage: String
)

val ENGLISH_STRINGS = JanSaarthiStrings(
    appTitle = "JanSaarthi",
    appSubtitle = "Citizen Welfare & Public Services Portal",
    govIndia = "Govt of India • Digital India",
    officialPortal = "Official Portal",
    verifiedBadge = "Verified",

    languageLabel = "Language:",
    textSizeLabel = "Text Size",
    normalSize = "A (Default)",
    largeSize = "A+ (Large)",

    citizenLogin = "Citizen Login",
    loginSubtitle = "Sign in to access public welfare benefits and certificates",
    withPasswordTab = "With Password",
    withOtpTab = "With OTP",
    mobileOrEmailLabel = "Mobile Number or Email",
    mobileOrEmailPlaceholder = "Enter 10-digit mobile or email",
    passwordLabel = "Password",
    passwordPlaceholder = "Enter your password",
    forgotPassword = "Forgot Password?",
    loginButton = "Login to JanSaarthi",
    sendOtpButton = "Send OTP to Mobile",
    verifyAndLoginButton = "Verify OTP & Login",
    enterOtpLabel = "Enter 6-digit OTP",
    sentViaSms = "Sent via SMS",
    resendOtpIn = "Resend OTP in",
    resendOtpButton = "Resend OTP",
    changeNumber = "Change Number",
    orDivider = "OR",
    continueAsGuest = "Continue as Guest",
    continueAsGuestSubtitle = "Explore public welfare schemes & services without signing in",
    newToJanSaarthi = "Don't have an account?",
    registerSignUp = "Register / Sign Up",

    citizenRegistration = "Citizen Registration",
    signUpSubtitle = "Enter basic details to create your secure citizen identity",
    fullNameLabel = "Full Legal Name",
    fullNamePlaceholder = "e.g. Ramesh Kumar Sharma",
    mobileNumberLabel = "Mobile Number (10 digits)",
    emailOptionalLabel = "Email Address (Optional)",
    chooseSecurityMethod = "Choose Security Setup",
    createPasswordTab = "Create Password",
    directOtpTab = "Direct OTP",
    confirmPasswordLabel = "Confirm Password",
    confirmPasswordPlaceholder = "Re-enter the same password",
    termsAgreementPre = "I agree to the ",
    termsOfService = "Terms of Service",
    andWord = " and ",
    privacyPolicy = "Citizen Privacy Policy",
    createAccountButton = "Create Citizen Account",
    alreadyRegistered = "Already have an account?",
    loginHere = "Login here",
    privacyPledge = "No Aadhaar or bank details required at registration. Protected under DPDP Act.",

    resetPasswordTitle = "Reset Password",
    resetPasswordSubtitle = "Enter your registered mobile or email to receive a password reset OTP",
    updatePasswordButton = "Update Password",
    resetSuccessTitle = "Password Updated Successfully!",
    resetSuccessSubtitle = "You can now login with your new password.",
    proceedToLogin = "Proceed to Login",

    stepProfileSetup = "Step 2 • Resident State Selection",
    stateSelectionTitle = "Select Your Resident State or UT",
    stateSelectionSubtitle = "Your resident state controls state-specific welfare schemes. Central schemes remain available nationwide.",
    searchStatePlaceholder = "Search state/UT, capital, or code...",
    allStatesTab = "All (36)",
    statesOnlyTab = "States (28)",
    utsOnlyTab = "Union Territories (8)",
    popularTab = "Popular States",
    selectedStateLabel = "Selected:",
    confirmStateButton = "Confirm State & Continue",
    changeStateLaterNote = "You can change your resident state later anytime from Profile.",
    capitalLabel = "Capital:",
    zoneLabel = "Zone:",
    unionTerritoryBadge = "UT",

    welcomeCitizen = "Welcome,",
    citizenWelfareTitle = "Citizen Welfare Portal",
    citizenWelfareSubtitle = "Displaying state welfare schemes alongside nationwide Central Government programs.",
    activeApplicationsLabel = "Active Applications",
    dbtStatusLabel = "DBT Status",
    dbtActive = "Active (Bank Linked)",
    searchSchemesPlaceholder = "Search welfare schemes (e.g. Kisan, Awas, Health)...",
    filterGovernanceLevel = "Filter Schemes by Governance Level:",
    allApplicableSchemes = "All Applicable",
    centralNationwide = "🇮🇳 Central (Nationwide)",
    stateSpecificSchemes = "🏛️ State Schemes",
    centralBadge = "🇮🇳 Central • Nationwide",
    stateBadge = "🏛️ State Scheme",
    guestModeActive = "Guest Mode Active",
    guestModeSubtitle = "Sign in anytime to unlock direct DBT transfers and certificates.",
    signInButton = "Sign In",
    changeStateLink = "Change",

    categoryFarmers = "Farmers (Kisan)",
    categoryHealthcare = "Healthcare",
    categoryHousing = "Housing (Awas)",
    categoryEducation = "Education",
    categoryPensions = "Pensions",
    categoryFood = "Food Security",

    schemeDetailsTitle = "Scheme Details & Eligibility",
    eligibilityHeader = "Eligibility Criteria",
    benefitsHeader = "Benefits & Subsidies",
    documentsHeader = "Required Documents",
    stepsHeader = "Application Steps",
    applyOnlineButton = "Apply on Official Portal",
    closeButton = "Close",

    profileTitle = "Citizen Profile",
    profileName = "Full Name:",
    profileMobile = "Mobile:",
    profileEmail = "Email:",
    profileResidentState = "Current Resident State / UT:",
    changeResidentStateButton = "Change Resident State",
    profileLanguageTitle = "App Display Language:",
    changeLanguageButton = "Change Language",
    selectLanguageTitle = "Choose App Language",
    signOutButton = "Sign Out",
    confirmSignOutTitle = "Confirm Sign Out",
    confirmSignOutMessage = "Are you sure you want to sign out of JanSaarthi?",
    cancelAction = "Cancel",

    citizenHelpdesk = "Citizen Helpdesk: 1800-11-0011 (Toll-Free, 24x7)",
    tollFreeNumber = "1800-11-0011",
    dpdpCompliant = "Compliant with Digital Personal Data Protection Act",
    nicAttribution = "Powered by National Informatics Centre (NIC)",

    notificationTitle = "Notifications & Announcements",
    notificationDbtAlert = "Next installment of welfare benefits scheduled for direct transfer this month.",
    notificationDeadlineAlert = "Annual renewal window open for state scholarships and agricultural equipment subsidies.",

    // Navigation
    navHome = "Home",
    navSchemes = "Schemes",
    navApplications = "Applications",
    navDocuments = "Documents",
    navProfile = "Profile",
    navBack = "Back",

    // Common Buttons
    applyNow = "Apply Now",
    checkEligibility = "Check My Scheme Eligibility",
    viewDetails = "View Details",
    saveScheme = "Save Scheme",
    savedBadge = "Saved",
    unsaveScheme = "Remove from Saved",
    downloadAction = "Download",
    uploadDocumentAction = "Upload Document",
    syncDigiLockerAction = "Sync DigiLocker",
    searchAction = "Search",
    filterAction = "Filter",
    clearFiltersAction = "Clear Filters",
    applyFiltersAction = "Apply Filters",
    resetFiltersAction = "Reset",
    retryAction = "Try Again",
    confirmAction = "Confirm & Proceed",
    submitAction = "Submit Application",
    exploreSchemesAction = "Explore Schemes",
    viewAllAction = "View All",
    trackStatusAction = "Track Status",
    shareAction = "Share",
    addDocumentAction = "Add Document",
    viewDocumentAction = "View Document",
    changeStateAction = "Change State",
    changeLanguageAction = "Change Language",

    // Labels & Badges
    centralGovernmentLabel = "Central Government",
    stateGovernmentLabel = "State Government",
    unionTerritoryLabel = "Union Territory",
    allSchemesLabel = "All Schemes",
    dbtActiveLabel = "DBT Active",
    verifiedStatusLabel = "Verified Citizen",
    requiredBadge = "Required",
    optionalBadge = "Optional",
    readyBadge = "Ready",
    missingBadge = "Missing",
    ministryLabel = "Ministry / Department",
    departmentLabel = "Department",
    benefitLabel = "Benefit Highlight",
    eligibilityLabel = "Eligibility Criteria",
    documentsRequiredLabel = "Required Documents",
    applicationProcessLabel = "Application Process",
    keyHighlightsLabel = "Key Highlights",
    lastUpdatedLabel = "Last Updated",
    readinessScoreLabel = "Document Readiness Score",
    referenceNumberLabel = "Application Reference Number",
    applicationDateLabel = "Application Date",
    prototypeDisclaimer = "Government Service Prototype • NIC Architecture",
    eligibleStatusLabel = "You are Eligible",
    familyBenefitLabel = "Family Benefit",
    conditionalMatchLabel = "Check Criteria",
    universalCitizenLabel = "Universal Citizen",
    overviewLabel = "Overview",

    // Filters & Tabs
    filterByLevelLabel = "Filter by Level",
    filterByCategoryLabel = "Filter by Category",
    filterByStateLabel = "Filter by State",
    sortByLabel = "Sort By",
    sortPopularityLabel = "Most Popular",
    sortAmountHighToLowLabel = "Benefit: High to Low",
    sortNewestLabel = "Recently Added",
    onlyDbtLabel = "Direct Benefit Transfer (DBT) Only",
    targetBeneficiaryLabel = "Target Beneficiary",
    allCategoriesLabel = "All Categories",
    allStatesLabel = "All States & UTs",
    allFilterLabel = "All",
    centralFilterLabel = "Central Government",
    stateFilterLabel = "State Government",
    utFilterLabel = "Union Territory",
    filterStatusDraft = "Draft",
    filterStatusApplied = "Applied",
    filterStatusUnderProcess = "Under Process",
    filterStatusApproved = "Approved",
    filterStatusRejected = "Rejected",
    filterStatusCompleted = "Completed",

    // Empty States
    noSchemesFoundTitle = "No Schemes Found",
    noSchemesFoundDesc = "Try adjusting your search keywords or clear active filters to view available welfare programs.",
    noApplicationsTitle = "No Applications Yet",
    noApplicationsDesc = "You have not submitted any scheme applications yet. Browse schemes and apply in simple steps.",
    noDocumentsTitle = "No Documents in Vault",
    noDocumentsDesc = "Sync with DigiLocker or upload your certificates for instantaneous eligibility verification.",
    noSavedSchemesTitle = "No Saved Schemes",
    noSavedSchemesDesc = "Bookmark schemes using the star icon on any card to review and apply for them later.",
    noSearchResultsTitle = "No Matching Search Results",
    noSearchResultsDesc = "We could not find any schemes matching your search. Try different terms or browse categories.",

    // Errors
    errorGenericTitle = "Something Went Wrong",
    errorGenericDesc = "Unable to complete the operation. Please check your network and try again.",
    errorNetworkTitle = "No Internet Connection",
    errorNetworkDesc = "Please connect to the internet to load updated government scheme information.",
    errorSubmissionFailed = "Application submission failed. Please verify all details and retry.",
    errorFillRequiredFields = "Please complete all mandatory fields before proceeding.",
    errorInvalidInput = "Invalid input entered. Please review your details.",

    // Help & Support
    helpTitle = "Citizen Helpdesk & Support",
    helpSubtitle = "Official national helpline and grievance redressal system",
    tollFreeHelplineLabel = "National Toll-Free Helpline: 1800-11-0011",
    helplineHoursLabel = "Available 24x7 in 12 Indian Languages",
    faqTitleLabel = "Frequently Asked Questions (FAQ)",
    contactUsLabel = "Contact Helpdesk",
    grievanceRedressalLabel = "Grievance Redressal (CPGRAMS)",
    dpdpActComplianceLabel = "Compliant with Digital Personal Data Protection Act 2023",

    // Settings
    settingsTitleLabel = "Profile & Settings",
    easyModeLabel = "Accessibility / Easy Mode",
    easyModeDesc = "Larger text, simpler navigation, and high contrast for seniors",
    languagePreferenceLabel = "Language Preference",
    notificationsSettingLabel = "Notifications & Alerts",
    privacySecurityLabel = "Privacy & Data Security",
    accountDetailsLabel = "Citizen Account Information",
    residentStateSettingLabel = "Resident State / UT",
    digiLockerStatusLabel = "DigiLocker Linked",
    aboutJanSaarthiTitle = "About JanSaarthi",
    aboutJanSaarthiDesc = "National unified single-window citizen welfare and public benefit discovery platform.",
    logoutDialogTitle = "Sign Out Confirmation",
    logoutDialogMessage = "Are you sure you want to sign out of JanSaarthi on this device?"
)

val HINDI_STRINGS = JanSaarthiStrings(
    appTitle = "जन सारथी",
    appSubtitle = "नागरिक कल्याण एवं सार्वजनिक सेवा पोर्टल",
    govIndia = "भारत सरकार • डिजिटल इंडिया",
    officialPortal = "आधिकारिक पोर्टल",
    verifiedBadge = "सत्यापित",

    languageLabel = "भाषा:",
    textSizeLabel = "फ़ॉन्ट आकार",
    normalSize = "A (सामान्य)",
    largeSize = "A+ (बड़ा)",

    citizenLogin = "नागरिक लॉगिन",
    loginSubtitle = "अपनी कल्याणकारी योजनाओं और सेवाओं तक पहुंचने के लिए लॉगिन करें",
    withPasswordTab = "पासवर्ड से",
    withOtpTab = "ओटीपी से",
    mobileOrEmailLabel = "मोबाइल नंबर या ईमेल",
    mobileOrEmailPlaceholder = "10 अंकों का मोबाइल या ईमेल दर्ज करें",
    passwordLabel = "पासवर्ड",
    passwordPlaceholder = "अपना पासवर्ड दर्ज करें",
    forgotPassword = "पासवर्ड भूल गए?",
    loginButton = "प्रवेश करें (लॉगिन)",
    sendOtpButton = "मोबाइल पर OTP भेजें",
    verifyAndLoginButton = "OTP सत्यापित करें एवं प्रवेश करें",
    enterOtpLabel = "6 अंकों का OTP दर्ज करें",
    sentViaSms = "एसएमएस द्वारा भेजा गया",
    resendOtpIn = "पुनः OTP भेजें",
    resendOtpButton = "OTP पुनः भेजें",
    changeNumber = "नंबर बदलें",
    orDivider = "अथवा",
    continueAsGuest = "अतिथि के रूप में जारी रखें",
    continueAsGuestSubtitle = "बिना लॉगिन के कल्याणकारी योजनाओं एवं सेवाओं को देखें",
    newToJanSaarthi = "नया खाता बनाना चाहते हैं?",
    registerSignUp = "पंजीकरण करें",

    citizenRegistration = "नागरिक पंजीकरण",
    signUpSubtitle = "सुरक्षित डिजिटल नागरिक पहचान बनाने के लिए बुनियादी विवरण दर्ज करें",
    fullNameLabel = "पूरा नाम",
    fullNamePlaceholder = "उदा. रमेश कुमार शर्मा",
    mobileNumberLabel = "मोबाइल नंबर (10 अंक)",
    emailOptionalLabel = "ईमेल आईडी (ऐच्छिक)",
    chooseSecurityMethod = "सुरक्षा विकल्प चुनें",
    createPasswordTab = "पासवर्ड बनाएं",
    directOtpTab = "सीधा ओटीपी",
    confirmPasswordLabel = "पासवर्ड की पुष्टि करें",
    confirmPasswordPlaceholder = "वही पासवर्ड पुनः दर्ज करें",
    termsAgreementPre = "मैं स्वीकार करता हूँ ",
    termsOfService = "नियम एवं शर्तें",
    andWord = " और ",
    privacyPolicy = "नागरिक गोपनीयता नीति",
    createAccountButton = "खाता बनाएं (पंजीकरण करें)",
    alreadyRegistered = "पहले से खाता है?",
    loginHere = "लॉगिन करें",
    privacyPledge = "पंजीकरण हेतु आधार या बैंक विवरण की आवश्यकता नहीं है। DPDP अधिनियम द्वारा संरक्षित।",

    resetPasswordTitle = "पासवर्ड रीसेट करें",
    resetPasswordSubtitle = "पासवर्ड रीसेट OTP प्राप्त करने के लिए पंजीकृत मोबाइल या ईमेल दर्ज करें",
    updatePasswordButton = "पासवर्ड अपडेट करें",
    resetSuccessTitle = "पासवर्ड सफलतापूर्वक बदला गया!",
    resetSuccessSubtitle = "अब आप अपने नए पासवर्ड से लॉगिन कर सकते हैं।",
    proceedToLogin = "लॉगिन पृष्ठ पर जाएं",

    stepProfileSetup = "चरण 2 • गृह राज्य चयन",
    stateSelectionTitle = "अपना गृह राज्य अथवा केंद्र शासित प्रदेश चुनें",
    stateSelectionSubtitle = "आपका राज्य चयन राज्य स्तरीय योजनाओं को निर्धारित करता है। केंद्रीय योजनाएं पूरे देश में उपलब्ध रहेंगी।",
    searchStatePlaceholder = "राज्य/यूटी, राजधानी या कोड खोजें...",
    allStatesTab = "सभी (36)",
    statesOnlyTab = "राज्य (28)",
    utsOnlyTab = "केंद्र शासित प्रदेश (8)",
    popularTab = "प्रमुख राज्य",
    selectedStateLabel = "चयनित:",
    confirmStateButton = "राज्य की पुष्टि करें एवं आगे बढ़ें",
    changeStateLaterNote = "आप बाद में कभी भी अपनी प्रोफ़ाइल से राज्य बदल सकते हैं।",
    capitalLabel = "राजधानी:",
    zoneLabel = "क्षेत्र:",
    unionTerritoryBadge = "यूटी",

    welcomeCitizen = "नमस्ते,",
    citizenWelfareTitle = "नागरिक कल्याण सेवा पोर्टल",
    citizenWelfareSubtitle = "आपके राज्य की विशिष्ट योजनाएं और राष्ट्रीय केंद्रीय योजनाएं नीचे प्रदर्शित हैं।",
    activeApplicationsLabel = "सक्रिय आवेदन",
    dbtStatusLabel = "डीबीटी स्थिति",
    dbtActive = "सक्रिय (बैंक लिंक)",
    searchSchemesPlaceholder = "कल्याणकारी योजनाएं खोजें (उदा. Kisan, Awas, Ladli)...",
    filterGovernanceLevel = "योजना स्तर के अनुसार फ़िल्टर करें:",
    allApplicableSchemes = "सभी लागू योजनाएं",
    centralNationwide = "🇮🇳 केंद्रीय (राष्ट्रव्यापी)",
    stateSpecificSchemes = "🏛️ राज्य योजनाएं",
    centralBadge = "🇮🇳 केंद्रीय • राष्ट्रव्यापी",
    stateBadge = "🏛️ राज्य योजना",
    guestModeActive = "अतिथि मोड सक्रिय",
    guestModeSubtitle = "सीधा डीबीटी और प्रमाण पत्र प्राप्त करने के लिए लॉगिन करें।",
    signInButton = "लॉगिन",
    changeStateLink = "बदलें",

    categoryFarmers = "किसान कल्याण",
    categoryHealthcare = "स्वास्थ्य सेवाएं",
    categoryHousing = "आवास योजनाएं",
    categoryEducation = "शिक्षा व छात्रवृत्ति",
    categoryPensions = "पेंशन व सहायता",
    categoryFood = "खाद्य सुरक्षा",

    schemeDetailsTitle = "योजना विवरण एवं पात्रता",
    eligibilityHeader = "पात्रता मानदंड",
    benefitsHeader = "प्राप्त होने वाले लाभ एवं वित्तीय सहायता",
    documentsHeader = "आवश्यक दस्तावेज",
    stepsHeader = "ऑनलाइन आवेदन प्रक्रिया",
    applyOnlineButton = "आधिकारिक पोर्टल पर आवेदन करें",
    closeButton = "बंद करें",

    profileTitle = "नागरिक प्रोफ़ाइल",
    profileName = "पूरा नाम:",
    profileMobile = "मोबाइल:",
    profileEmail = "ईमेल:",
    profileResidentState = "वर्तमान गृह राज्य / यूटी:",
    changeResidentStateButton = "गृह राज्य बदलें",
    profileLanguageTitle = "ऐप की भाषा:",
    changeLanguageButton = "भाषा बदलें",
    selectLanguageTitle = "ऐप की भाषा चुनें",
    signOutButton = "लॉगआउट करें",
    confirmSignOutTitle = "लॉगआउट की पुष्टि",
    confirmSignOutMessage = "क्या आप JanSaarthi से लॉगआउट करना चाहते हैं?",
    cancelAction = "रद्द करें",

    citizenHelpdesk = "नागरिक सहायता डेस्क: 1800-11-0011 (टोल-फ्री, 24x7)",
    tollFreeNumber = "1800-11-0011",
    dpdpCompliant = "डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम के अनुरूप",
    nicAttribution = "राष्ट्रीय सूचना विज्ञान केंद्र (NIC) द्वारा संचालित",

    notificationTitle = "सूचनाएं एवं सरकारी घोषणाएं",
    notificationDbtAlert = "कल्याणकारी योजनाओं की अगली किस्त इस माह सीधे खाते में भेजी जाएगी।",
    notificationDeadlineAlert = "राज्य छात्रवृत्ति एवं कृषि उपकरणों पर सब्सिडी हेतु आवेदन विंडो खुली है।",

    // Navigation
    navHome = "होम",
    navSchemes = "योजनाएं",
    navApplications = "आवेदन",
    navDocuments = "दस्तावेज़",
    navProfile = "प्रोफ़ाइल",
    navBack = "पीछे",

    // Common Buttons
    applyNow = "अभी आवेदन करें",
    checkEligibility = "मेरी पात्रता जांचें",
    viewDetails = "विवरण देखें",
    saveScheme = "योजना सहेजें",
    savedBadge = "सहेजा गया",
    unsaveScheme = "हटाएं",
    downloadAction = "डाउनलोड करें",
    uploadDocumentAction = "दस्तावेज़ अपलोड करें",
    syncDigiLockerAction = "डिजीलॉकर सिंक करें",
    searchAction = "खोजें",
    filterAction = "फ़िल्टर",
    clearFiltersAction = "फ़िल्टर हटाएं",
    applyFiltersAction = "फ़िल्टर लागू करें",
    resetFiltersAction = "रीसेट करें",
    retryAction = "पुनः प्रयास करें",
    confirmAction = "पुष्टि करें एवं आगे बढ़ें",
    submitAction = "आवेदन जमा करें",
    exploreSchemesAction = "योजनाएं देखें",
    viewAllAction = "सभी देखें",
    trackStatusAction = "स्थिति ट्रैक करें",
    shareAction = "साझा करें",
    addDocumentAction = "दस्तावेज़ जोड़ें",
    viewDocumentAction = "दस्तावेज़ देखें",
    changeStateAction = "राज्य बदलें",
    changeLanguageAction = "भाषा बदलें",

    // Labels & Badges
    centralGovernmentLabel = "केंद्र सरकार",
    stateGovernmentLabel = "राज्य सरकार",
    unionTerritoryLabel = "केंद्र शासित प्रदेश",
    allSchemesLabel = "सभी योजनाएं",
    dbtActiveLabel = "डीबीटी सक्रिय",
    verifiedStatusLabel = "सत्यापित नागरिक",
    requiredBadge = "अनिवार्य",
    optionalBadge = "वैकल्पिक",
    readyBadge = "तैयार",
    missingBadge = "अनुपलब्ध",
    ministryLabel = "मंत्रालय / विभाग",
    departmentLabel = "विभाग",
    benefitLabel = "प्राप्त लाभ",
    eligibilityLabel = "पात्रता मानदंड",
    documentsRequiredLabel = "आवश्यक दस्तावेज़",
    applicationProcessLabel = "आवेदन प्रक्रिया",
    keyHighlightsLabel = "मुख्य विशेषताएं",
    lastUpdatedLabel = "अंतिम अद्यतन",
    readinessScoreLabel = "दस्तावेज़ तत्परता स्कोर",
    referenceNumberLabel = "आवेदन संदर्भ संख्या",
    applicationDateLabel = "आवेदन तिथि",
    prototypeDisclaimer = "सरकारी सेवा प्रोटोटाइप • एनआईसी संरचना",
    eligibleStatusLabel = "आप पात्र हैं",
    familyBenefitLabel = "परिवार लाभ",
    conditionalMatchLabel = "पात्रता जांचें",
    universalCitizenLabel = "सार्वभौमिक नागरिक",
    overviewLabel = "अवलोकन",

    // Filters & Tabs
    filterByLevelLabel = "स्तर अनुसार फ़िल्टर",
    filterByCategoryLabel = "श्रेणी अनुसार फ़िल्टर",
    filterByStateLabel = "राज्य अनुसार फ़िल्टर",
    sortByLabel = "क्रमबद्ध करें",
    sortPopularityLabel = "सर्वाधिक लोकप्रिय",
    sortAmountHighToLowLabel = "लाभ: अधिक से कम",
    sortNewestLabel = "हाल ही में जोड़ी गई",
    onlyDbtLabel = "केवल प्रत्यक्ष लाभ अंतरण (DBT)",
    targetBeneficiaryLabel = "लक्षित लाभार्थी",
    allCategoriesLabel = "सभी श्रेणियां",
    allStatesLabel = "सभी राज्य एवं यूटी",
    allFilterLabel = "सभी",
    centralFilterLabel = "केंद्र सरकार",
    stateFilterLabel = "राज्य सरकार",
    utFilterLabel = "केंद्र शासित प्रदेश",
    filterStatusDraft = "प्रारूप",
    filterStatusApplied = "आवेदित",
    filterStatusUnderProcess = "प्रक्रियाधीन",
    filterStatusApproved = "स्वीकृत",
    filterStatusRejected = "अस्वीकृत",
    filterStatusCompleted = "पूर्ण",

    // Empty States
    noSchemesFoundTitle = "कोई योजना नहीं मिली",
    noSchemesFoundDesc = "कृपया अपनी खोज बदलें या अधिक योजनाएं देखने के लिए फ़िल्टर हटाएं।",
    noApplicationsTitle = "अभी कोई आवेदन नहीं है",
    noApplicationsDesc = "आपने अभी तक किसी योजना के लिए आवेदन नहीं किया है। योजनाएं देखें और सरलता से आवेदन करें।",
    noDocumentsTitle = "वॉल्ट में कोई दस्तावेज़ नहीं है",
    noDocumentsDesc = "त्वरित पात्रता जांच के लिए डिजीलॉकर से सिंक करें या अपने पहचान पत्र अपलोड करें।",
    noSavedSchemesTitle = "कोई सहेजी गई योजना नहीं",
    noSavedSchemesDesc = "बाद में देखने और आवेदन करने के लिए स्टार आइकन से योजनाओं को सहेजें।",
    noSearchResultsTitle = "कोई परिणाम नहीं मिला",
    noSearchResultsDesc = "आपके खोज मानदंडों से मेल खाती कोई योजना नहीं मिली। कृपया अन्य शब्द आज़माएं।",

    // Errors
    errorGenericTitle = "कुछ गड़बड़ हो गई",
    errorGenericDesc = "प्रक्रिया पूरी करने में असमर्थ। कृपया अपना नेटवर्क जांचें और पुनः प्रयास करें।",
    errorNetworkTitle = "इंटरनेट कनेक्शन उपलब्ध नहीं है",
    errorNetworkDesc = "नवीनतम सरकारी योजना जानकारी लोड करने के लिए कृपया इंटरनेट से जुड़ें।",
    errorSubmissionFailed = "आवेदन जमा करने में विफल। कृपया विवरण जांचें और पुनः प्रयास करें।",
    errorFillRequiredFields = "कृपया आगे बढ़ने से पहले सभी अनिवार्य फ़ील्ड भरें।",
    errorInvalidInput = "अमान्य इनपुट दर्ज किया गया है। कृपया अपने विवरण की समीक्षा करें।",

    // Help & Support
    helpTitle = "नागरिक सहायता एवं समर्थन",
    helpSubtitle = "आधिकारिक राष्ट्रीय हेल्पलाइन एवं शिकायत निवारण प्रणाली",
    tollFreeHelplineLabel = "राष्ट्रीय टोल-फ्री हेल्पलाइन: 1800-11-0011",
    helplineHoursLabel = "12 भारतीय भाषाओं में 24x7 उपलब्ध",
    faqTitleLabel = "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
    contactUsLabel = "हेल्पडेस्क से संपर्क करें",
    grievanceRedressalLabel = "शिकायत निवारण (CPGRAMS)",
    dpdpActComplianceLabel = "डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम 2023 के अनुरूप",

    // Settings
    settingsTitleLabel = "प्रोफ़ाइल एवं सेटिंग्स",
    easyModeLabel = "सुगमता / सरल मोड",
    easyModeDesc = "वरिष्ठ नागरिकों हेतु बड़े अक्षर, सरल नेविगेशन और उच्च स्पष्टता",
    languagePreferenceLabel = "भाषा प्राथमिकता",
    notificationsSettingLabel = "अलर्ट एवं सूचनाएं",
    privacySecurityLabel = "गोपनीयता एवं डेटा सुरक्षा",
    accountDetailsLabel = "नागरिक खाता विवरण",
    residentStateSettingLabel = "गृह राज्य / केंद्र शासित प्रदेश",
    digiLockerStatusLabel = "डिजीलॉकर से जुड़ा हुआ",
    aboutJanSaarthiTitle = "JanSaarthi के बारे में",
    aboutJanSaarthiDesc = "नागरिक कल्याण एवं सार्वजनिक लाभ खोज हेतु राष्ट्रीय एकल-खिड़की डिजिटल मंच।",
    logoutDialogTitle = "लॉगआउट की पुष्टि",
    logoutDialogMessage = "क्या आप इस डिवाइस पर JanSaarthi से लॉगआउट करना चाहते हैं?"
)

val MARATHI_STRINGS = HINDI_STRINGS.copy(
    appTitle = "जन सारथी",
    welcomeCitizen = "नमस्कार,",
    appSubtitle = "नागरी कल्याण व सार्वजनिक सेवा पोर्टल",
    govIndia = "भारत सरकार • डिजिटल इंडिया",
    citizenLogin = "नागरिक लॉगिन",
    loginSubtitle = "कल्याणकारी योजना व सेवांचा लाभ घेण्यासाठी लॉगिन करा",
    withPasswordTab = "पासवर्डने",
    withOtpTab = "ओटीपीने",
    mobileOrEmailLabel = "मोबाईल नंबर किंवा ईमेल",
    passwordLabel = "पासवर्ड",
    forgotPassword = "पासवर्ड विसरलात?",
    loginButton = "प्रवेश करा",
    continueAsGuest = "अतिथी म्हणून सुरू ठेवा",
    continueAsGuestSubtitle = "लॉगिन न करता योजना व सेवांची माहिती पहा",
    newToJanSaarthi = "नवीन खाते तयार करायचे आहे?",
    registerSignUp = "नोंदणी करा",
    citizenRegistration = "नागरिक नोंदणी",
    fullNameLabel = "पूर्ण नाव",
    confirmPasswordLabel = "पासवर्डची पुष्टी करा",
    termsOfService = "नियम व अटी",
    privacyPolicy = "गोपनीयता धोरण",
    createAccountButton = "खाते तयार करा",
    alreadyRegistered = "आधीच खाते आहे?",
    stateSelectionTitle = "आपले रहिवासी राज्य निवडा",
    stateSelectionSubtitle = "आपल्या राज्यानुसार राज्यस्तरीय योजना दिसतील. केंद्रीय योजना संपूर्ण देशात उपलब्ध आहेत.",
    searchStatePlaceholder = "राज्य/केंद्रशासित प्रदेश शोधा...",
    allStatesTab = "सर्व (36)",
    statesOnlyTab = "राज्ये (28)",
    utsOnlyTab = "केंद्रशासित प्रदेश (8)",
    confirmStateButton = "राज्याची पुष्टी करा व पुढे जा",
    changeStateLaterNote = "तुम्ही नंतर कधीही प्रोफाईलवरून राज्य बदलू शकता.",
    allApplicableSchemes = "सर्व लागू योजना",
    centralNationwide = "🇮🇳 केंद्रीय योजना",
    stateSpecificSchemes = "🏛️ राज्य योजना",
    categoryFarmers = "शेतकरी कल्याण",
    categoryHealthcare = "आरोग्य सेवा",
    categoryHousing = "गृहनिर्माण योजना",
    categoryEducation = "शिक्षण व शिष्यवृत्ती",
    categoryPensions = "पेन्शन व सहाय्य",
    eligibilityHeader = "पात्रता निकष",
    benefitsHeader = "मिळणारे लाभ",
    documentsHeader = "आवश्यक कागदपत्रे",
    stepsHeader = "अर्ज करण्याची पद्धत",
    profileTitle = "नागरिक प्रोफाईल",
    changeResidentStateButton = "राज्य बदला",
    changeLanguageButton = "भाषा बदला",
    selectLanguageTitle = "अॅपची भाषा निवडा",
    signOutButton = "लॉगआउट",
    navHome = "होम",
    navSchemes = "योजना",
    navApplications = "अर्ज",
    navDocuments = "कागदपत्रे",
    navProfile = "प्रोफाईल",
    applyNow = "आता अर्ज करा",
    checkEligibility = "पात्रता तपासा",
    viewDetails = "तपशील पहा",
    saveScheme = "योजना जतन करा",
    savedBadge = "जतन केले",
    allSchemesLabel = "सर्व योजना",
    centralGovernmentLabel = "केंद्र सरकार",
    stateGovernmentLabel = "राज्य सरकार",
    unionTerritoryLabel = "केंद्रशासित प्रदेश",
    noSchemesFoundTitle = "कोणतीही योजना सापडली नाही",
    noApplicationsTitle = "अद्याप कोणतेही अर्ज नाहीत",
    noDocumentsTitle = "तिजोरीत कागदपत्रे नाहीत",
    noSavedSchemesTitle = "जतन केलेल्या योजना नाहीत",
    settingsTitleLabel = "सेटिंग्ज",
    easyModeLabel = "सुलभ मोड"
)

val TAMIL_STRINGS = ENGLISH_STRINGS.copy(
    appTitle = "ஜன்சாரதி",
    welcomeCitizen = "வணக்கம்,",
    appSubtitle = "குடிமக்கள் நலன் மற்றும் பொது சேவை தளம்",
    govIndia = "இந்திய அரசு • டிஜிட்டல் இந்தியா",
    citizenLogin = "குடிமக்கள் உள்நுழைவு",
    loginSubtitle = "அரசு நலத்திட்டங்களை அணுக உள்நுழையவும்",
    loginButton = "உள்நுழைக",
    continueAsGuest = "விருந்தினராக தொடரவும்",
    registerSignUp = "பதிவு செய்க",
    citizenRegistration = "குடிமக்கள் பதிவு",
    fullNameLabel = "முழு பெயர்",
    stateSelectionTitle = "உங்கள் வசிப்பிட மாநிலத்தை தேர்வு செய்யவும்",
    confirmStateButton = "மாநிலத்தை உறுதிசெய்து தொடரவும்",
    allApplicableSchemes = "அனைத்து திட்டங்கள்",
    centralNationwide = "🇮🇳 மத்திய அரசு திட்டங்கள்",
    stateSpecificSchemes = "🏛️ மாநில திட்டங்கள்",
    categoryFarmers = "விவசாயிகள் நலன்",
    categoryHealthcare = "சுகாதார சேவைகள்",
    categoryHousing = "வீட்டுவசதி திட்டங்கள்",
    categoryEducation = "கல்வி மற்றும் உதவித்தொகை",
    categoryPensions = "ஓய்வூதியம்",
    eligibilityHeader = "தகுதி வரம்புகள்",
    benefitsHeader = "திட்டத்தின் பயன்கள்",
    documentsHeader = "தேவையான ஆவணங்கள்",
    stepsHeader = "விண்ணப்பிக்கும் முறை",
    profileTitle = "குடிமக்கள் சுயவிவரம்",
    changeResidentStateButton = "மாநிலத்தை மாற்றுக",
    changeLanguageButton = "மொழியை மாற்றுக",
    selectLanguageTitle = "பயன்பாட்டு மொழியை தேர்வு செய்க",
    signOutButton = "வெளியேறு",
    navHome = "முகப்பு",
    navSchemes = "திட்டங்கள்",
    navApplications = "விண்ணப்பங்கள்",
    navDocuments = "ஆவணங்கள்",
    navProfile = "சுயவிவரம்",
    applyNow = "இப்போதே விண்ணப்பிக்கவும்",
    checkEligibility = "தகுதியை சரிபார்க்கவும்",
    viewDetails = "விவரங்களை காண்க",
    saveScheme = "சேமிக்கவும்",
    savedBadge = "சேமிக்கப்பட்டது",
    allSchemesLabel = "அனைத்து திட்டங்கள்",
    centralGovernmentLabel = "மத்திய அரசு",
    stateGovernmentLabel = "மாநில அரசு",
    noSchemesFoundTitle = "திட்டங்கள் எதுவும் காணப்படவில்லை",
    noApplicationsTitle = "விண்ணப்பங்கள் எதுவும் இல்லை",
    settingsTitleLabel = "அமைப்புகள்",
    easyModeLabel = "எளிய முறை"
)

val TELUGU_STRINGS = ENGLISH_STRINGS.copy(
    appTitle = "జనసారథి",
    welcomeCitizen = "నమస్కారం,",
    appSubtitle = "పౌర సంక్షేమం మరియు ప్రభుత్వ సేవల పోర్టల్",
    govIndia = "భారత ప్రభుత్వం • డిజిటల్ ఇండియా",
    citizenLogin = "పౌరుల లాగిన్",
    loginSubtitle = "ప్రభుత్వ సంక్షేమ పథకాలను పొందడానికి లాగిన్ అవ్వండి",
    loginButton = "లాగిన్ అవ్వండి",
    continueAsGuest = "అతిథిగా కొనసాగండి",
    registerSignUp = "నమోదు చేసుకోండి",
    citizenRegistration = "పౌరుల నమోదు",
    fullNameLabel = "పూర్తి పేరు",
    stateSelectionTitle = "మీ నివాస రాష్ట్రాన్ని ఎంచుకోండి",
    confirmStateButton = "రాష్ట్రాన్ని నిర్ధారించి కొనసాగండి",
    allApplicableSchemes = "అన్ని వర్తించే పథకాలు",
    centralNationwide = "🇮🇳 కేంద్ర ప్రభుత్వ పథకాలు",
    stateSpecificSchemes = "🏛️ రాష్ట్ర పథకాలు",
    categoryFarmers = "రైతు సంక్షేమం",
    categoryHealthcare = "ఆరోగ్య సేవలు",
    categoryHousing = "గృహనిర్మాణ పథకాలు",
    categoryEducation = "విద్య మరియు స్కాలర్‌షిప్‌లు",
    categoryPensions = "పింఛన్లు",
    eligibilityHeader = "అర్హత ప్రమాణాలు",
    benefitsHeader = "పథకం ప్రయోజనాలు",
    documentsHeader = "అవసరమైన పత్రాలు",
    stepsHeader = "దరఖాస్తు విధానం",
    profileTitle = "పౌరుడి ప్రొఫైల్",
    changeResidentStateButton = "రాష్ట్రాన్ని మార్చండి",
    changeLanguageButton = "భాషను మార్చండి",
    selectLanguageTitle = "యాప్ భాషను ఎంచుకోండి",
    signOutButton = "లాగ్ అవుట్",
    navHome = "హోమ్",
    navSchemes = "పథకాలు",
    navApplications = "దరఖాస్తులు",
    navDocuments = "పత్రాలు",
    navProfile = "ప్రొఫైల్",
    applyNow = "ఇప్పుడే దరఖాస్తు చేసుకోండి",
    checkEligibility = "అర్హతను తనిఖీ చేయండి",
    viewDetails = "వివరాలు చూడండి",
    saveScheme = "పథకాన్ని భద్రపరచండి",
    savedBadge = "భద్రపరచబడింది",
    allSchemesLabel = "అన్ని పథకాలు",
    centralGovernmentLabel = "కేంద్ర ప్రభుత్వం",
    stateGovernmentLabel = "రాష్ట్ర ప్రభుత్వం",
    noSchemesFoundTitle = "పథకాలు ఏవీ కనుగొనబడలేదు",
    noApplicationsTitle = "ఇంకా ఎటువంటి దరఖాస్తులు లేవు",
    settingsTitleLabel = "సెట్టింగ్‌లు",
    easyModeLabel = "సులభ మోడ్"
)

val BENGALI_STRINGS = ENGLISH_STRINGS.copy(
    appTitle = "জনসারথী",
    welcomeCitizen = "নমস্কার,",
    appSubtitle = "নাগরিক কল্যাণ ও সরকারি পরিষেবা পোর্টাল",
    govIndia = "ভারত সরকার • ডিজিটাল ইন্ডিয়া",
    citizenLogin = "নাগরিক লগইন",
    loginSubtitle = "সরকারি কল্যাণমূলক প্রকল্প ও পরিষেবা দেখতে লগইন করুন",
    loginButton = "লগইন করুন",
    continueAsGuest = "অতিথি হিসেবে এগিয়ে যান",
    registerSignUp = "নিবন্ধন করুন",
    citizenRegistration = "নাগরিক নিবন্ধন",
    fullNameLabel = "পুরো নাম",
    stateSelectionTitle = "আপনার রাজ্য নির্বাচন করুন",
    confirmStateButton = "রাজ্য নিশ্চিত করে এগিয়ে যান",
    allApplicableSchemes = "সমস্ত প্রযোজ্য প্রকল্প",
    centralNationwide = "🇮🇳 কেন্দ্রীয় সরকারি প্রকল্প",
    stateSpecificSchemes = "🏛️ রাজ্য প্রকল্প",
    categoryFarmers = "কৃষক কল্যাণ",
    categoryHealthcare = "স্বাস্থ্য পরিষেবা",
    categoryHousing = "আবাসন প্রকল্প",
    categoryEducation = "শিক্ষা ও বৃত্তি",
    categoryPensions = "পেনশন",
    eligibilityHeader = "যোগ্যতার মানদণ্ড",
    benefitsHeader = "প্রকল্পের সুবিধাসমূহ",
    documentsHeader = "প্রয়োজনীয় নথিপত্র",
    stepsHeader = "আবেদন প্রক্রিয়া",
    profileTitle = "নাগরিক প্রোফাইল",
    changeResidentStateButton = "রাজ্য পরিবর্তন করুন",
    changeLanguageButton = "ভাষা পরিবর্তন করুন",
    selectLanguageTitle = "অ্যাপের ভাষা নির্বাচন করুন",
    signOutButton = "সাইন আউট",
    navHome = "হোম",
    navSchemes = "প্রকল্প",
    navApplications = "আবেদন",
    navDocuments = "নথিপত্র",
    navProfile = "প্রোফাইল",
    applyNow = "এখনই আবেদন করুন",
    checkEligibility = "যোগ্যতা যাচাই করুন",
    viewDetails = "বিস্তারিত দেখুন",
    saveScheme = "সংরক্ষণ করুন",
    savedBadge = "সংরক্ষিত",
    allSchemesLabel = "সমস্ত প্রকল্প",
    centralGovernmentLabel = "কেন্দ্রীয় সরকার",
    stateGovernmentLabel = "রাজ্য সরকার",
    noSchemesFoundTitle = "কোনো প্রকল্প পাওয়া যায়নি",
    noApplicationsTitle = "এখনও কোনো আবেদন নেই",
    settingsTitleLabel = "সেটিংস",
    easyModeLabel = "সহজ মোড"
)

val GUJARATI_STRINGS = ENGLISH_STRINGS.copy(
    appTitle = "જનસારથી",
    welcomeCitizen = "નમસ્તે,",
    appSubtitle = "નાગરિક કલ્યાણ અને જાહેર સેવા પોર્ટલ",
    govIndia = "ભારત સરકાર • ડિજિટલ ઇન્ડિયા",
    citizenLogin = "નાગરિક લૉગિન",
    loginSubtitle = "સરકારી યોજનાઓ અને સેવાઓ મેળવવા લૉગિન કરો",
    loginButton = "લૉગિન કરો",
    continueAsGuest = "અતિથિ તરીકે આગળ વધો",
    registerSignUp = "નોંધણી કરો",
    citizenRegistration = "નાગરિક નોંધણી",
    fullNameLabel = "પૂરું નામ",
    stateSelectionTitle = "તમારું રાજ્ય પસંદ કરો",
    confirmStateButton = "રાજ્ય પુષ્ટિ કરો અને આગળ વધો",
    allApplicableSchemes = "તમામ લાગુ યોજનાઓ",
    centralNationwide = "🇮🇳 કેન્દ્રીય યોજનાઓ",
    stateSpecificSchemes = "🏛️ રાજ્ય યોજનાઓ",
    categoryFarmers = "ખેડૂત કલ્યાણ",
    categoryHealthcare = "આરોગ્ય સેવાઓ",
    categoryHousing = "આવાસ યોજનાઓ",
    categoryEducation = "શિક્ષણ અને શિષ્યવૃત્તિ",
    categoryPensions = "પેન્શન",
    eligibilityHeader = "પાત્રતાના માપદંડ",
    benefitsHeader = "યોજનાના ફાયદા",
    documentsHeader = "જરૂરી દસ્તાવેજો",
    stepsHeader = "અરજી કરવાની પ્રક્રિયા",
    profileTitle = "નાગરિક પ્રોફાઇલ",
    changeResidentStateButton = "રાજ્ય બદલો",
    changeLanguageButton = "ભાષા બદલો",
    selectLanguageTitle = "એપ્લિકેશનની ભાષા પસંદ કરો",
    signOutButton = "સાઇન આઉટ",
    navHome = "હોમ",
    navSchemes = "યોજનાઓ",
    navApplications = "અરજીઓ",
    navDocuments = "દસ્તાવેજો",
    navProfile = "પ્રોફાઇલ",
    applyNow = "હમણાં અરજી કરો",
    checkEligibility = "પાત્રતા ચકાસો",
    viewDetails = "વિગતો જુઓ",
    saveScheme = "સાચવો",
    savedBadge = "સાચવેલ",
    allSchemesLabel = "બધી યોજનાઓ",
    centralGovernmentLabel = "કેન્દ્ર સરકાર",
    stateGovernmentLabel = "રાજ્ય સરકાર",
    noSchemesFoundTitle = "કોઈ યોજના મળી નથી",
    noApplicationsTitle = "હજુ સુધી કોઈ અરજી નથી",
    settingsTitleLabel = "સેટિંગ્સ",
    easyModeLabel = "સરળ મોડ"
)

val KANNADA_STRINGS = ENGLISH_STRINGS.copy(
    appTitle = "ಜನಸಾರಥಿ",
    welcomeCitizen = "ನಮಸ್ಕಾರ,",
    appSubtitle = "ನಾಗರಿಕ ಕಲ್ಯಾಣ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸೇವಾ ಪೋರ್ಟಲ್",
    govIndia = "ಭಾರತ ಸರ್ಕಾರ • ಡಿಜಿಟಲ್ ಇಂಡಿಯಾ",
    citizenLogin = "ನಾಗರಿಕ ಲಾಗಿನ್",
    loginSubtitle = "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಪಡೆಯಲು ಲಾಗಿನ್ ಮಾಡಿ",
    loginButton = "ಲಾಗಿನ್ ಮಾಡಿ",
    continueAsGuest = "ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ",
    registerSignUp = "ನೋಂದಣಿ ಮಾಡಿ",
    citizenRegistration = "ನಾಗರಿಕ ನೋಂದಣಿ",
    fullNameLabel = "ಪೂರ್ಣ ಹೆಸರು",
    stateSelectionTitle = "ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    confirmStateButton = "ರಾಜ್ಯ ದೃಢೀಕರಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ",
    allApplicableSchemes = "ಎಲ್ಲಾ ಅನ್ವಯವಾಗುವ ಯೋಜನೆಗಳು",
    centralNationwide = "🇮🇳 ಕೇಂದ್ರ ಸರ್ಕಾರದ ಯೋಜನೆಗಳು",
    stateSpecificSchemes = "🏛️ ರಾಜ್ಯ ಯೋಜನೆಗಳು",
    categoryFarmers = "ರೈತ ಕಲ್ಯಾಣ",
    categoryHealthcare = "ಆರೋಗ್ಯ ಸೇವೆಗಳು",
    categoryHousing = "ವಸತಿ ಯೋಜನೆಗಳು",
    categoryEducation = "ಶಿಕ್ಷಣ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿವೇತನ",
    categoryPensions = "ಪಿಂಚಣಿ",
    eligibilityHeader = "ಅರ್ಹತಾ ಮಾನದಂಡಗಳು",
    benefitsHeader = "ಯೋಜನೆಯ ಪ್ರಯೋಜನಗಳು",
    documentsHeader = "ಅಗತ್ಯ ದಾಖಲೆಗಳು",
    stepsHeader = "ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ವಿಧಾನ",
    profileTitle = "ನಾಗರಿಕ ಪ್ರೊಫೈಲ್",
    changeResidentStateButton = "ರಾಜ್ಯವನ್ನು ಬದಲಾಯಿಸಿ",
    changeLanguageButton = "ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಿ",
    selectLanguageTitle = "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    signOutButton = "ಸೈನ್ ಔಟ್",
    navHome = "ಮುಖಪುಟ",
    navSchemes = "ಯೋಜನೆಗಳು",
    navApplications = "ಅರ್ಜಿಗಳು",
    navDocuments = "ದಾಖಲೆಗಳು",
    navProfile = "ಪ್ರೊಫೈಲ್",
    applyNow = "ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    checkEligibility = "ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ",
    viewDetails = "ವಿವರಗಳನ್ನು ನೋಡಿ",
    saveScheme = "ಉಳಿಸಿ",
    savedBadge = "ಉಳಿಸಲಾಗಿದೆ",
    allSchemesLabel = "ಎಲ್ಲಾ ಯೋಜನೆಗಳು",
    centralGovernmentLabel = "ಕೇಂದ್ರ ಸರ್ಕಾರ",
    stateGovernmentLabel = "ರಾಜ್ಯ ಸರ್ಕಾರ",
    noSchemesFoundTitle = "ಯಾವುದೇ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    noApplicationsTitle = "ಇನ್ನೂ ಯಾವುದೇ ಅರ್ಜಿಗಳಿಲ್ಲ",
    settingsTitleLabel = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    easyModeLabel = "ಸುಲಭ ಮೋಡ್"
)

/**
 * Returns strongly typed localized strings dictionary for the selected AppLanguage.
 * Default is English.
 */
fun getJanSaarthiStrings(language: AppLanguage): JanSaarthiStrings {
    return when (language) {
        AppLanguage.ENGLISH -> ENGLISH_STRINGS
        AppLanguage.HINDI -> HINDI_STRINGS
        AppLanguage.MARATHI -> MARATHI_STRINGS
        AppLanguage.TAMIL -> TAMIL_STRINGS
        AppLanguage.TELUGU -> TELUGU_STRINGS
        AppLanguage.BENGALI -> BENGALI_STRINGS
        AppLanguage.GUJARATI -> GUJARATI_STRINGS
        AppLanguage.KANNADA -> KANNADA_STRINGS
        AppLanguage.PUNJABI -> HINDI_STRINGS.copy(
            welcomeCitizen = "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ,",
            appTitle = "ਜਨ ਸਾਰਥੀ",
            navHome = "ਘਰ",
            navSchemes = "ਯੋਜਨਾਵਾਂ",
            navApplications = "ਅਰਜ਼ੀਆਂ",
            navDocuments = "ਦਸਤਾਵੇਜ਼",
            navProfile = "ਪ੍ਰੋਫਾਈਲ"
        )
        AppLanguage.ODIA -> BENGALI_STRINGS.copy(
            welcomeCitizen = "ନମସ୍କାର,",
            appTitle = "ଜନସାରଥୀ",
            navHome = "ହୋମ୍",
            navSchemes = "ଯୋଜନା",
            navApplications = "ଆବେଦନ",
            navDocuments = "ଦସ୍ତାବିଜ",
            navProfile = "ପ୍ରୋଫାଇଲ୍"
        )
        AppLanguage.MALAYALAM -> TAMIL_STRINGS.copy(
            welcomeCitizen = "നമസ്കാരം,",
            appTitle = "ജനസാരഥി",
            navHome = "ഹോം",
            navSchemes = "പദ്ധതികൾ",
            navApplications = "അപേക്ഷകൾ",
            navDocuments = "രേഖകൾ",
            navProfile = "പ്രൊഫൈൽ"
        )
    }
}
